server:
    port: 9198


#database
spring:
    devtools:
        restart:
            enabled: false

    redis:
        host: 127.0.0.1
        port: 6479

druid:
    datasource:
        username: root
        password: root$%^
        url: jdbc:mysql://127.0.0.1:3306/zeus?useUnicode=true&characterEncoding=UTF-8
        driverClassName: com.mysql.jdbc.Driver

static:
    image:
        download:
            path: /var/zeus/static/upload
        url: http://zeus-static.zunpeng.org/